[mypy]
python_version = 3.11
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = True
disable_error_code = empty-body,var-annotated,arg-type,assignment,attr-defined,call-overload,import-untyped,import-not-found
