from setuptools import setup, find_packages

setup(
    name="unified-space-debris-detection",
    version="0.1.0",
    description="Unified multi-modal space debris detection with cross-modal attention and physics-informed deep learning.",
    author="Your Name",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "torch==2.2.0",
        "numpy==1.26.4",
        "scipy==1.12.0",
        "scikit-learn==1.4.1",
        "matplotlib==3.8.3",
        "pandas==2.2.1",
        "opencv-python==4.9.0.80",
        "wandb==0.16.3",
        "optuna==3.5.0",
        "sgp4==2.22",
        "pyyaml==6.0.1",
        "seaborn==0.13.2",
        "albumentations==1.4.0",
        "omegaconf==2.3.0",
        "pytest==8.1.1",
        "coverage==7.4.4",
        "black==24.2.0",
        "ruff==0.3.4",
        "mypy==1.9.0",
        "onnx==1.16.0",
        "torchvision==0.17.0",
        "transformers==4.39.3",
        "azure-identity==1.17.1",
        "azure-keyvault-secrets==4.8.0",
    ],
    python_requires=">=3.11,<3.12",
)
